# LaTeX CI

name: Compile manual LaTeX

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build LaTeX
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: manual/
          root_file: main.tex

      # Uploads compiled PDF
      - name: Run a multi-line script
        uses: actions/upload-artifact@v2
        with:
          name: Manual
          path: manual/main.pdf

